version: 2

jobs:
  build-test:
    working_directory: ~/repo
    docker:
      - image: rust:1.42-buster
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            apt-get update
            apt install -y python3-pip libopenblas-dev gfortran
            python3.7 -m pip install tox 'setuptools-rust>=0.6.0'
            rustup default nightly-2020-03-01
      - run:
          name: install
          command: |
            python3.7 setup.py install
      - run:
          name: test
          command: |
            set -x
            cd /tmp/
            python3.7 -m pip install pytest pytest-faulthandler
            python3.7 -m pytest --pyargs argmin
            cd -

  lint:
    working_directory: ~/repo
    docker:
      - image: rust:1.42-buster
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            apt-get update
            apt install -y python3-pip libopenblas-dev gfortran
            python3.7 -m pip install tox 'setuptools-rust>=0.6.0' black
            rustup default nightly-2020-03-01
            rustup component add rustfmt
      - run:
          name: cargo fmt
          command: cargo fmt -- --check
      - run:
          name: black
          command: black --check examples/ argmin/


workflows:
  version: 2
  build:
    jobs:
      - build-test
      - lint
