version: 2

jobs:
  build-test:
    working_directory: ~/repo
    docker:
      - image: konstin2/pyo3-pack:0.5.0
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            python3.7 -m pip install tox 'setuptools-rust>=0.6.0'
            rustup default nightly-2019-06-04
      - run:
          name: install
          command: |
            python3.7 setup.py install
      - run:
          name: test
          command: |
            cd /tmp/
            python3.7 -m pip install pytest pytest-faulthandler
            python3.7 -m pytest --pyargs argmin
            cd -

workflows:
  version: 2
  build:
    jobs:
      - build-test
